name: Update Formula
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update to (e.g., 0.1.1)'
        required: true
      tag:
        description: 'GitHub release tag (e.g., v0.1.1)'
        required: true
jobs:
  update:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout tap
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Homebrew (Linux)
        run: |
          NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      
      - name: Update formula
        run: |
          FORMULA="Formula/nettracex.rb"
          VERSION="${{ github.event.inputs.version }}"
          TAG="${{ github.event.inputs.tag }}"
          
          echo "Downloading and calculating SHA256 hashes..."
          DARWIN_ARM64_SHA=$(curl -sL "https://github.com/nettracex/nettracex-tui/releases/download/${TAG}/nettracex-${TAG}-darwin-arm64" | sha256sum | cut -d' ' -f1)
          DARWIN_AMD64_SHA=$(curl -sL "https://github.com/nettracex/nettracex-tui/releases/download/${TAG}/nettracex-${TAG}-darwin-amd64" | sha256sum | cut -d' ' -f1)
          LINUX_ARM64_SHA=$(curl -sL "https://github.com/nettracex/nettracex-tui/releases/download/${TAG}/nettracex-${TAG}-linux-arm64" | sha256sum | cut -d' ' -f1)
          LINUX_AMD64_SHA=$(curl -sL "https://github.com/nettracex/nettracex-tui/releases/download/${TAG}/nettracex-${TAG}-linux-amd64" | sha256sum | cut -d' ' -f1)
          
          echo "Darwin ARM64: ${DARWIN_ARM64_SHA}"
          echo "Darwin AMD64: ${DARWIN_AMD64_SHA}"
          echo "Linux ARM64: ${LINUX_ARM64_SHA}"
          echo "Linux AMD64: ${LINUX_AMD64_SHA}"
          
          # Update version
          sed -i "s/version \".*\"/version \"${VERSION}\"/" "$FORMULA"
          
          # Update URLs
          sed -i "s|nettracex-v[0-9.]*-darwin-arm64|nettracex-${TAG}-darwin-arm64|g" "$FORMULA"
          sed -i "s|nettracex-v[0-9.]*-darwin-amd64|nettracex-${TAG}-darwin-amd64|g" "$FORMULA"
          sed -i "s|nettracex-v[0-9.]*-linux-arm64|nettracex-${TAG}-linux-arm64|g" "$FORMULA"
          sed -i "s|nettracex-v[0-9.]*-linux-amd64|nettracex-${TAG}-linux-amd64|g" "$FORMULA"
          
          # Update SHA256 values using awk for more precise replacement
          awk -v arm64="$DARWIN_ARM64_SHA" -v amd64="$DARWIN_AMD64_SHA" '
            /on_macos/,/^  end/ {
              if (/Hardware::CPU\.arm\?/) { in_arm=1; in_amd=0 }
              if (/else/ && in_arm) { in_arm=0; in_amd=1 }
              if (/sha256/ && in_arm) { sub(/sha256 ".*"/, "sha256 \"" arm64 "\"") }
              if (/sha256/ && in_amd) { sub(/sha256 ".*"/, "sha256 \"" amd64 "\"") }
              if (/^  end/) { in_arm=0; in_amd=0 }
            }
            { print }
          ' "$FORMULA" > "${FORMULA}.tmp" && mv "${FORMULA}.tmp" "$FORMULA"
          
          awk -v arm64="$LINUX_ARM64_SHA" -v amd64="$LINUX_AMD64_SHA" '
            /on_linux/,/^  end/ {
              if (/Hardware::CPU\.arm\?/) { in_arm=1; in_amd=0 }
              if (/else/ && in_arm) { in_arm=0; in_amd=1 }
              if (/sha256/ && in_arm) { sub(/sha256 ".*"/, "sha256 \"" arm64 "\"") }
              if (/sha256/ && in_amd) { sub(/sha256 ".*"/, "sha256 \"" amd64 "\"") }
              if (/^  end/) { in_arm=0; in_amd=0 }
            }
            { print }
          ' "$FORMULA" > "${FORMULA}.tmp" && mv "${FORMULA}.tmp" "$FORMULA"
          
          echo "=== Updated Formula ==="
          cat "$FORMULA"
      
      - name: Audit formula
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          
          # Link the tap manually
          REPO_OWNER="${GITHUB_REPOSITORY%/*}"
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          mkdir -p "$(brew --repository)/Library/Taps/${REPO_OWNER}"
          ln -s "${GITHUB_WORKSPACE}" "$(brew --repository)/Library/Taps/${REPO_OWNER}/homebrew-${REPO_NAME}"
          
          brew audit --strict --online nettracex || true
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "nettracex ${{ github.event.inputs.version }}"
          title: "nettracex ${{ github.event.inputs.version }}"
          body: |
            Update nettracex to version ${{ github.event.inputs.version }}
            
            Release: https://github.com/nettracex/nettracex-tui/releases/tag/${{ github.event.inputs.tag }}
            
            ## Changes
            - Updated version to `${{ github.event.inputs.version }}`
            - Updated all binary URLs to release tag `${{ github.event.inputs.tag }}`
            - Updated SHA256 checksums for all platforms
          branch: update-nettracex-${{ github.event.inputs.version }}
          delete-branch: true
