name: brew pr-pull
on:
  pull_request_target:
    types:
      - labeled
jobs:
  pr-pull-linux:
    if: contains(github.event.pull_request.labels.*.name, 'pr-pull')
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      checks: read
      contents: write
      issues: read
      pull-requests: write
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up git
        uses: Homebrew/actions/git-user-config@main
      
      - name: Pull bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew pr-pull --debug --tap="$GITHUB_REPOSITORY" "$PULL_REQUEST"
      
      - name: Push commits
        uses: Homebrew/actions/git-try-push@main
        with:
          branch: main
      
      - name: Delete branch
        if: github.event.pull_request.head.repo.fork == false
        env:
          BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          git push --delete origin "$BRANCH"
  
  pr-pull-macos:
    if: contains(github.event.pull_request.labels.*.name, 'pr-pull')
    runs-on: macos-latest
    permissions:
      actions: read
      checks: read
      contents: write
      issues: read
      pull-requests: write
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up git
        uses: Homebrew/actions/git-user-config@main
      
      - name: Pull bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}
        run: |
          if [[ -f /opt/homebrew/bin/brew ]]; then
            eval "$(/opt/homebrew/bin/brew shellenv)"
          else
            eval "$(/usr/local/bin/brew shellenv)"
          fi
          brew pr-pull --debug --tap="$GITHUB_REPOSITORY" "$PULL_REQUEST"
      
      - name: Push commits
        uses: Homebrew/actions/git-try-push@main
        with:
          branch: main
      
      - name: Delete branch
        if: github.event.pull_request.head.repo.fork == false
        env:
          BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          if [[ -f /opt/homebrew/bin/brew ]]; then
            eval "$(/opt/homebrew/bin/brew shellenv)"
          else
            eval "$(/usr/local/bin/brew shellenv)"
          fi
          git push --delete origin "$BRANCH"
