name: Test Formula
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, macos-15-intel, macos-26 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout tap
        uses: actions/checkout@v4
      
      - name: Set up Homebrew (macOS)
        if: runner.os == 'macOS'
        run: |
          # Homebrew is pre-installed on macOS runners
          brew update
      
      - name: Set up Homebrew (Linux)
        if: runner.os == 'Linux'
        run: |
          # Install Homebrew on Linux
          NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      
      - name: Tap this repository
        run: |
          REPO_PATH="${GITHUB_WORKSPACE}"
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          REPO_OWNER="${GITHUB_REPOSITORY%/*}"
          
          # Create tap directory structure
          mkdir -p "$(brew --repository)/Library/Taps/${REPO_OWNER}"
          ln -s "${REPO_PATH}" "$(brew --repository)/Library/Taps/${REPO_OWNER}/homebrew-${REPO_NAME}"
      
      - name: Install and test formula
        run: |
          brew install nettracex
          brew test nettracex
          brew audit --strict nettracex
