name: Test Formula
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-15-intel, macos-26 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Tap repository
        run: brew tap ${{ github.repository }}
      
      - name: Install formula
        run: brew install nettracex
      
      - name: Test formula
        run: brew test nettracex
      
      - name: Audit formula
        run: brew audit --strict --online nettracex
      
      - name: Test binary execution
        run: |
          nettracex --version || true
          nettracex --help || true
